### ISSUE TITLE
For new benchmark problems how to produce the corresponding csv files?

### ISSUE THREAD

**Issue by Weining-Cao** [jyao15/G-CLN#2]
I want to run G-CLN on some new benchmark problems, but I cannot find the right .py file like "instrument.py" in cln2inv to produce corresponding csv files.

**Comment by jyao15** [comment]
Unfortunately G-CLN does not have a universal sampling process. For a new program, you can use "instrument.py" from cln2inv as a starting point then edit the instrumented C file as you wish.
